CREATE TABLE tasks (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    uid TEXT NOT NULL,
    href TEXT,
    etag TEXT,
    server_version INTEGER NOT NULL DEFAULT 1,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    completed_at DATETIME,
    due_date DATE,
    due_at DATETIME,
    priority INTEGER,
    rrule TEXT,
    parent_id TEXT,
    raw_vtodo TEXT NOT NULL,
    base_vtodo TEXT,
    label_names TEXT,
    project_name TEXT,
    sync_status TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects(id),
    FOREIGN KEY(parent_id) REFERENCES tasks(id)
);
